
### Create New User 
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "emaill@gmail.com",
   "password": "emaill"
}

### Sign In User
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "email@gmail.com",
   "password": "email"
}


### GEZ Current User
GET http://localhost:3000/auth/whoami


### Sign Out User
POST http://localhost:3000/auth/signout



### FInd User by ID
GET http://localhost:3000/auth/1

### FInd User by Email
GET http://localhost:3000/auth?email=kaiser@gmail.com

### Update User by ID
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "kaiser_updated@gmail.com",
   "password": "nahid_updated"
}


###Delete User by ID
DELETE http://localhost:3000/auth/24